package com.junolabs.usm.persistence.dao;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public interface IConnectionManager {

	public PreparedStatement prepareStatement(String sql) throws SQLException;
	
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;
	
	public Statement statement(String sql) throws SQLException;
	
	public void setAutoCommit(boolean autoCommit) throws SQLException;
	
	public void commit() throws SQLException;
    
	public void rollback() throws SQLException;
    
	public void close() throws SQLException;

}
